language: node_js
node_js: "10.15"
cache: yarn

_production-job: &production-job
  stage: production
  name: SERVICE_NAME
  script: scripts/deploy.js SERVICE_NAME
  install: skip
  env:
    - "ENVIRONMENT=production RANCHER_CLUSTERID=c-njflm"

stages:
  - name: test

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: test
      env: [NODE_ENV=test]

    - <<: *production-job
      stage: production-started
      name: Deployment Started
      script: npx @parameter1/base-cms-website-deployment-tool notify-started

    #############################
    ### vvv ADD SITES HERE vvv ##
    #############################

    - <<: *production-job
      name: greenindustrypros.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy greenindustrypros.com websites

    - <<: *production-job
      name: sdcexec.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy sdcexec.com websites

    - <<: *production-job
      name: mixequipmentmag.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy mixequipmentmag.com websites

    - <<: *production-job
      name: foodlogistics.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy foodlogistics.com websites

    - <<: *production-job
      name: oemoffhighway.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy oemoffhighway.com websites

    - <<: *production-job
      name: dmnews.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy dmnews.com websites

    - <<: *production-job
      name: forconstructionpros.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy forconstructionpros.com websites

    - <<: *production-job
      name: safesecureopenings.com
      script: npx @parameter1/base-cms-website-deployment-tool deploy safesecureopenings.com websites

    #############################
    ### ^^^ ADD SITES HERE ^^^ ##
    #############################

    - <<: *production-job
      stage: production-finished
      name: Deployment Finished
      script: npx @parameter1/base-cms-website-deployment-tool notify-finished
