version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.21
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  OMEDA_APP_ID: ${OMEDA_APP_ID-(unset)}
  OMEDA_INPUT_ID: ${OMEDA_INPUT_ID-(unset)}
  OMEDA_GRAPHQL_URI: ${OMEDA_GRAPHQL_URI-https://graphql.omeda.parameter1.com}
  RECAPTCHA_V3_SITE_KEY: ${RECAPTCHA_V3_SITE_KEY-(unset)}
  RECAPTCHA_V3_SECRET_KEY: ${RECAPTCHA_V3_SECRET_KEY-(unset)}
  ENABLE_CONTENT_METER: ${ENABLE_CONTENT_METER-false}
  SPEC_GUIDE_DOCS_API_KEY: ${SPEC_GUIDE_DOCS_API_KEY-(unset)}
  SENDGRID_API_KEY: ${SENDGRID_API_KEY-(unset)}
  SENDGRID_DEV_TO: ${SENDGRID_DEV_TO-support@parameter1.com}
  YARN_CACHE_FOLDER: /.yarn-cache
  IDENTITYX_API_TOKEN: ${IDENTITYX_API_TOKEN-(unset)}
  BASE_BROWSE_GRAPHQL_URI: ${BASE_BROWSE_GRAPHQL_URI-https://base-browse.tauron.base.parameter1.com/graphql}
  NATIVEX_SERVE_URI: ${NATIVEX_SERVE_URI-}

x-env-tauron: &env-tauron
  GRAPHQL_URI: ${GRAPHQL_URI-https://tauron.graphql.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://tauron.oembed.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://tauron.rss.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://tauron.sitemaps.base.parameter1.com}

x-env-leonis: &env-leonis
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.leonis.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://oembed.leonis.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://rss.leonis.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://sitemaps.leonis.base.parameter1.com}

x-env-development: &env-development
  GRAPHQL_URI: ${GRAPHQL_URI-http://host.docker.internal:10002}
  OEMBED_URI: ${OEMBED_URI-http://host.docker.internal:10013}
  RSS_URI: ${RSS_URI-http://host.docker.internal:10011}
  SITEMAPS_URI: ${SITEMAPS_URI-http://host.docker.internal:10009}

x-site-command: &site-cmd
  <<: *node
  entrypoint: ["yarn"]
  command: ["dev"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  gip:
    <<: *site-cmd
    working_dir: /root/sites/greenindustrypros.com
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 9710
      LIVERELOAD_PORT: 19710
      OMEDA_INPUT_ID: ${GIP_OMEDA_INPUT_ID-(unset)}
      HOST: www-acbm-gip.dev.parameter1.com
    hostname: www-acbm-gip.dev.parameter1.com
    ports:
      - "9710:80"
      - "19710:19710"

  sdc:
    <<: *site-cmd
    working_dir: /root/sites/sdcexec.com
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 9711
      LIVERELOAD_PORT: 19711
      OMEDA_INPUT_ID: ${SDC_OMEDA_INPUT_ID-(unset)}
      HOST: www-acbm-sdc.dev.parameter1.com
    hostname: www-acbm-sdc.dev.parameter1.com
    ports:
      - "9711:80"
      - "19711:19711"
  fl:
    <<: *site-cmd
    working_dir: /root/sites/foodlogistics.com
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 9713
      LIVERELOAD_PORT: 19713
      OMEDA_INPUT_ID: ${FL_OMEDA_INPUT_ID-(unset)}
      HOST: www-acbm-fl.dev.parameter1.com
    hostname: www-acbm-fl.dev.parameter1.com
    ports:
      - "9713:80"
      - "19713:19713"

  oem:
    <<: *site-cmd
    working_dir: /root/sites/oemoffhighway.com
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 9714
      LIVERELOAD_PORT: 19714
      OMEDA_INPUT_ID: ${OEM_OMEDA_INPUT_ID-(unset)}
      HOST: www-acbm-oem.dev.parameter1.com
    hostname: www-acbm-oem.dev.parameter1.com
    ports:
      - "9714:80"
      - "19714:19714"

  fcp:
    <<: *site-cmd
    working_dir: /root/sites/forconstructionpros.com
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 9716
      LIVERELOAD_PORT: 19716
      OMEDA_INPUT_ID: ${FCP_OMEDA_INPUT_ID-(unset)}
      HOST: www-acbm-fcp.dev.parameter1.com
    hostname: www-acbm-fcp.dev.parameter1.com
    ports:
      - "9716:80"
      - "19716:19716"

  rental:
    <<: *site-cmd
    working_dir: /root/sites/rentalproductnews.com
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 9719
      LIVERELOAD_PORT: 19719
      OMEDA_INPUT_ID: ${RENTAL_OMEDA_INPUT_ID-(unset)}
      HOST: www-acbm-rental.dev.parameter1.com
    hostname: www-acbm-rental.dev.parameter1.com
    ports:
      - "9719:80"
      - "19719:19719"

  fcp-g:
    <<: *site-cmd
    working_dir: /root/sites/forconstructionpros-global.com
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 9721
      LIVERELOAD_PORT: 19721
      OMEDA_INPUT_ID: ${FCP_OMEDA_INPUT_ID-(unset)}
      HOST: www-acbm-fcp-g.dev.parameter1.com
    hostname: www-acbm-fcp-g.dev.parameter1.com
    ports:
      - "9721:80"
      - "19721:19721"

  ip:
    <<: *site-cmd
    working_dir: /root/sites/ironpros.com
    environment:
      <<: [*env, *env-leonis]
      PORT: 80
      EXPOSED_PORT: 9723
      LIVERELOAD_PORT: 19723
      OMEDA_INPUT_ID: ${IP_OMEDA_INPUT_ID-(unset)}
      IRONPROS_PRODUCT_SPECS_SERVICE_URL: ${IRONPROS_PRODUCT_SPECS_SERVICE_URL-}
      BASE_BROWSE_GRAPHQL_URI: ${IP_BASE_BROWSE_GRAPHQL_URI-https://base-browse.leonis.base.parameter1.com/graphql}
      HOST: www-acbm-ip.dev.parameter1.com
    hostname: www-acbm-ip.dev.parameter1.com
    ports:
      - "9723:80"
      - "19723:19723"

  ironpros-product-specs:
    <<: *node
    working_dir: /root/services/ironpros-product-specs
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      HOST: ironpros-product-specs-api.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 23355
      MONGO_URL: ${MONGO_URL-}
      MONGO_DB: ${MONGO_DB-ironpros}
    hostname: ironpros-product-specs-api.dev.parameter1.com
    ports:
      - "23355:80"
