name: Deploy sites (production)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - id: tag_version
      run: |
        REF=$(echo $GITHUB_REF | cut -d / -f 3)
        [[ "$GITHUB_REF" =~ ^refs/tags.*$ ]] && VERSION="$REF" || VERSION="${REF}-${GITHUB_SHA::7}"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.tag_version.outputs.version }}

  notify-start:
    needs: [version]
    uses: parameter1/actions/.github/workflows/notify-start.yml@main
    secrets: inherit
    with:
      version: ${{ needs.version.outputs.version }}

  post-deploy-failure:
    if: failure()
    needs: [notify-start, deploy-sites]
    uses: parameter1/actions/.github/workflows/notify-fail.yml@main
    secrets: inherit
    with:
      slack-thread: ${{ needs.notify-start.outputs.slack-thread }}

  post-deploy-complete:
    if: success()
    needs: [notify-start, deploy-sites]
    uses: parameter1/actions/.github/workflows/notify-complete.yml@main
    secrets: inherit
    with:
      slack-thread: ${{ needs.notify-start.outputs.slack-thread }}

  ######################
  # Add websites here! #
  ######################

  build-sites:
    needs: [version]
    uses: parameter1/actions/.github/workflows/website-build-push-test.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { id: 53c95f4a1784f8066eb2c86a, dir: foodlogistics.com, stack: tauron, account: acbm, tenant: acbm_scn, rancher_label: ac-business-media-foodlogistics.com }
          - { id: 53ca8d671784f8066eb2c949, dir: forconstructionpros.com, stack: tauron, account: acbm, tenant: acbm_fcp, rancher_label: ac-business-media-forconstructionpros.com }
          - { id: 53c95fdd1784f8066eb2c891, dir: greenindustrypros.com, stack: tauron, account: acbm, tenant: acbm_gip, rancher_label: ac-business-media-greenindustrypros.com }
          - { id: 54b5a261c99db54158ed0fc9, dir: oemoffhighway.com, stack: tauron, account: acbm, tenant: acbm_ooh, rancher_label: ac-business-media-oemoffhighway.com }
          - { id: 53ca8d671784f8066eb2c949, dir: rentalproductnews.com, stack: tauron, account: acbm, tenant: acbm_fcp, rancher_label: ac-business-media-rentalproductnews.com }
          - { id: 5f09fe3771f65a24008b456e, dir: safesecureopenings.com, stack: tauron, account: acbm, tenant: acbm_fcp, rancher_label: ac-business-media-safesecureopenings.com }
          - { id: 53c960451784f8066eb2c8a4, dir: sdcexec.com, stack: tauron, account: acbm, tenant: acbm_scn, rancher_label: ac-business-media-sdcexec.com }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      ecr_registry: ${{ vars.AWS_ECR_REGISTRY }}
      push: true
      site_account: ${{ matrix.site.account }}
      site_dir: ${{ matrix.site.dir }}
      site_version: ${{ needs.version.outputs.version }}
    secrets: inherit

  deploy-sites:
    needs: [version, build-sites]
    uses: parameter1/actions/.github/workflows/website-deploy-production.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { id: 53c95f4a1784f8066eb2c86a, dir: foodlogistics.com, stack: tauron, account: acbm, tenant: acbm_scn, rancher_label: ac-business-media-foodlogistics.com }
          - { id: 53ca8d671784f8066eb2c949, dir: forconstructionpros.com, stack: tauron, account: acbm, tenant: acbm_fcp, rancher_label: ac-business-media-forconstructionpros.com }
          - { id: 53c95fdd1784f8066eb2c891, dir: greenindustrypros.com, stack: tauron, account: acbm, tenant: acbm_gip, rancher_label: ac-business-media-greenindustrypros.com }
          - { id: 54b5a261c99db54158ed0fc9, dir: oemoffhighway.com, stack: tauron, account: acbm, tenant: acbm_ooh, rancher_label: ac-business-media-oemoffhighway.com }
          - { id: 53ca8d671784f8066eb2c949, dir: rentalproductnews.com, stack: tauron, account: acbm, tenant: acbm_fcp, rancher_label: ac-business-media-rentalproductnews.com }
          - { id: 5f09fe3771f65a24008b456e, dir: safesecureopenings.com, stack: tauron, account: acbm, tenant: acbm_fcp, rancher_label: ac-business-media-safesecureopenings.com }
          - { id: 53c960451784f8066eb2c8a4, dir: sdcexec.com, stack: tauron, account: acbm, tenant: acbm_scn, rancher_label: ac-business-media-sdcexec.com }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      ecr_registry: ${{ vars.AWS_ECR_REGISTRY }}
      rancher_label: ${{ matrix.site.rancher_label }}
      site_account: ${{ matrix.site.account }}
      site_dir: ${{ matrix.site.dir }}
      site_stack: ${{ matrix.site.stack }}
      site_version: ${{ needs.version.outputs.version }}
    secrets: inherit
