name: Integration Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test-image:
    uses: parameter1/actions/.github/workflows/website-build-push-test.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { id: 53c95f4a1784f8066eb2c86a, dir: foodlogistics.com, stack: tauron, account: acbm, tenant: acbm_scn, rancher_label: ac-business-media-foodlogistics.com }
          - { id: 53ca8d671784f8066eb2c949, dir: forconstructionpros.com, stack: tauron, account: acbm, tenant: acbm_fcp, rancher_label: ac-business-media-forconstructionpros.com }
          - { id: 53c95fdd1784f8066eb2c891, dir: greenindustrypros.com, stack: tauron, account: acbm, tenant: acbm_gip, rancher_label: ac-business-media-greenindustrypros.com }
          - { id: 54b5a261c99db54158ed0fc9, dir: oemoffhighway.com, stack: tauron, account: acbm, tenant: acbm_ooh, rancher_label: ac-business-media-oemoffhighway.com }
          - { id: 53ca8d671784f8066eb2c949, dir: rentalproductnews.com, stack: tauron, account: acbm, tenant: acbm_fcp, rancher_label: ac-business-media-rentalproductnews.com }
          - { id: 5f09fe3771f65a24008b456e, dir: safesecureopenings.com, stack: tauron, account: acbm, tenant: acbm_fcp, rancher_label: ac-business-media-safesecureopenings.com }
          - { id: 53c960451784f8066eb2c8a4, dir: sdcexec.com, stack: tauron, account: acbm, tenant: acbm_scn, rancher_label: ac-business-media-sdcexec.com }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      docker_image: website-${{ matrix.site.dir }}
      site_id: ${{ matrix.site.id }}
      site_host: ${{ matrix.site.dir }}
      infra_stack: ${{ matrix.site.stack }}
      tenant_key: ${{ matrix.site.tenant }}
      ecr_registry: ${{ vars.AWS_ECR_REGISTRY }}
